<?xml version="1.0" encoding="utf-8"?><Database Name="Biblioteka" Class="BibliotekaSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-FNT9N89\ISBD;Initial Catalog=Biblioteka;Integrated Security=True" SettingsObjectName="Biblioteka.Properties.Settings" SettingsPropertyName="BibliotekaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Wypozyczone" Member="Wypozyczone">
    <Type Name="Wypozyczone">
      <Column Name="IDHistorii" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EgzemplarzID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UzytkownikID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Data_wyp" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Data_zwr" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PracownikID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Czytelnik_Wypozyczone" Member="Czytelnik" ThisKey="PracownikID" OtherKey="IDUzytkownika" Type="Czytelnik" IsForeignKey="true" />
      <Association Name="Egzemplarz_Wypozyczone" Member="Egzemplarz" ThisKey="EgzemplarzID" OtherKey="IDEgzeplarza" Type="Egzemplarz" IsForeignKey="true" />
      <Association Name="Pracownik_Wypozyczone" Member="Pracownik" ThisKey="PracownikID" OtherKey="IDPracownika" Type="Pracownik" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Autor" Member="Autor">
    <Type Name="Autor">
      <Column Name="IDAutor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Imie" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Nazwisko" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="NarodowoscID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Data_ur" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Data_sm" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EpokaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Autor_AutorzyKsiazek" Member="AutorzyKsiazek" ThisKey="IDAutor" OtherKey="AutorID" Type="AutorzyKsiazek" />
      <Association Name="Epoka_Autor" Member="Epoka" ThisKey="EpokaID" OtherKey="IDEpoka" Type="Epoka" IsForeignKey="true" />
      <Association Name="Narodowosc_Autor" Member="Narodowosc" ThisKey="NarodowoscID" OtherKey="IDNarodowosc" Type="Narodowosc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AutorzyKsiazek" Member="AutorzyKsiazek">
    <Type Name="AutorzyKsiazek">
      <Column Name="IDAutorzy" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AutorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KsiazkaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Autor_AutorzyKsiazek" Member="Autor" ThisKey="AutorID" OtherKey="IDAutor" Type="Autor" IsForeignKey="true" />
      <Association Name="Ksiazka_AutorzyKsiazek" Member="Ksiazka" ThisKey="KsiazkaID" OtherKey="IDKsiazki" Type="Ksiazka" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Czytelnik" Member="Czytelnik">
    <Type Name="Czytelnik">
      <Column Name="IDUzytkownika" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ImieU" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NazwiskoU" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Ulica" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Miasto" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Nr_domu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Login" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Haslo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Czytelnik_Wypozyczone" Member="Wypozyczone" ThisKey="IDUzytkownika" OtherKey="PracownikID" Type="Wypozyczone" />
      <Association Name="Czytelnik_Rezerwacja" Member="Rezerwacja" ThisKey="IDUzytkownika" OtherKey="UzytkownikID" Type="Rezerwacja" />
    </Type>
  </Table>
  <Table Name="dbo.Egzemplarz" Member="Egzemplarz">
    <Type Name="Egzemplarz">
      <Column Name="IDEgzeplarza" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KsiazkaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Egzemplarz_Wypozyczone" Member="Wypozyczone" ThisKey="IDEgzeplarza" OtherKey="EgzemplarzID" Type="Wypozyczone" />
      <Association Name="Egzemplarz_Rezerwacja" Member="Rezerwacja" ThisKey="IDEgzeplarza" OtherKey="EgzemplarzID" Type="Rezerwacja" />
      <Association Name="Ksiazka_Egzemplarz" Member="Ksiazka" ThisKey="KsiazkaID" OtherKey="IDKsiazki" Type="Ksiazka" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Epoka" Member="Epoka">
    <Type Name="Epoka">
      <Column Name="IDEpoka" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NazwaEpoki" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="Epoka_Autor" Member="Autor" ThisKey="IDEpoka" OtherKey="EpokaID" Type="Autor" />
    </Type>
  </Table>
  <Table Name="dbo.Gatunek" Member="Gatunek">
    <Type Name="Gatunek">
      <Column Name="IDGatunek" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NazwaGatunku" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Gatunek_Ksiazka" Member="Ksiazka" ThisKey="IDGatunek" OtherKey="GatunekID" Type="Ksiazka" />
    </Type>
  </Table>
  <Table Name="dbo.Ksiazka" Member="Ksiazka">
    <Type Name="Ksiazka">
      <Column Name="IDKsiazki" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tytul" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="AutorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WydawnictwoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ISBN" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Ilosc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rok" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GatunekID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Ksiazka_AutorzyKsiazek" Member="AutorzyKsiazek" ThisKey="IDKsiazki" OtherKey="KsiazkaID" Type="AutorzyKsiazek" />
      <Association Name="Ksiazka_Egzemplarz" Member="Egzemplarz" ThisKey="IDKsiazki" OtherKey="KsiazkaID" Type="Egzemplarz" />
      <Association Name="Gatunek_Ksiazka" Member="Gatunek" ThisKey="GatunekID" OtherKey="IDGatunek" Type="Gatunek" IsForeignKey="true" />
      <Association Name="Wydawnictwo_Ksiazka" Member="Wydawnictwo" ThisKey="WydawnictwoID" OtherKey="IDWydawnictwo" Type="Wydawnictwo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Narodowosc" Member="Narodowosc">
    <Type Name="Narodowosc">
      <Column Name="IDNarodowosc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NazwaNarodowosci" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Narodowosc_Autor" Member="Autor" ThisKey="IDNarodowosc" OtherKey="NarodowoscID" Type="Autor" />
    </Type>
  </Table>
  <Table Name="dbo.Pracownik" Member="Pracownik">
    <Type Name="Pracownik">
      <Column Name="IDPracownika" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoginP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HasloP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Pracownik_Wypozyczone" Member="Wypozyczone" ThisKey="IDPracownika" OtherKey="PracownikID" Type="Wypozyczone" />
    </Type>
  </Table>
  <Table Name="dbo.Rezerwacja" Member="Rezerwacja">
    <Type Name="Rezerwacja">
      <Column Name="IDRezerwacja" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UzytkownikID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EgzemplarzID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DataRez" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Egzemplarz_Rezerwacja" Member="Egzemplarz" ThisKey="EgzemplarzID" OtherKey="IDEgzeplarza" Type="Egzemplarz" IsForeignKey="true" />
      <Association Name="Czytelnik_Rezerwacja" Member="Czytelnik" ThisKey="UzytkownikID" OtherKey="IDUzytkownika" Type="Czytelnik" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Wydawnictwo" Member="Wydawnictwo">
    <Type Name="Wydawnictwo">
      <Column Name="IDWydawnictwo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NazwaWyd" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="Wydawnictwo_Ksiazka" Member="Ksiazka" ThisKey="IDWydawnictwo" OtherKey="WydawnictwoID" Type="Ksiazka" />
    </Type>
  </Table>
</Database>